### PR TITLE
HexTest.exe deleted because it is virus-infected

### PR DESCRIPTION
**Pull request by m-h-asfour**
HexTest.exe deleted because it is virus-infected

### CODE REVIEW

**Comment by bubach** [comment]
It doesn't, and no antivirus knows about DexOS apps/formats anyway. Hell, antiviruses hardly work on "normal" PE-files...

**Comment by m-h-asfour** [comment]
I am an ex-computer engineer in Egypt. My past experience was trying to assist companies and a bank to make applications. That was about a quarter of a century ago and mainly on machines that they called "mainframes", and of course that had nothing to do with viruses. Now I'm just a very shallow "normal" user and despite this fact, I can hardly bear being forced to use more of such machines and such software. I have Avira antivirus (free edition of course) installed together with Microsoft security essentials and what remained from "Hitman" after his successful mission and the end of the free period. I downloaded DexOs zip file, and tried to unzip it using 7zip. It used to hang when it reaches hextext.exe, then Avira started to generate an increasing number of alerts for viruses that exceed its limit for the free edition, while Microsoft essentials used to display a message saying "no action needed". I tried to just unpack the zip more than once and every time I had to turn off the PC during this process. Apparently it was some sort of a loop, and every time no more alerts were generated after the reboot until I retry to unzip. I faced the same situation even when I tried to unzip the newly downloaded zipped file that github created from your repository.  Now, after the removal of this EXE, the zip file was unzipped successfully without any alerts at all. So, although I do not consider myself an expert in viruses, I have every very convincing reason to believe that hextest.exe is the "problem". I still did not even try to use DexOs yet and I still do not know how important is that EXE file for it, but please try to do something if you can.

**Comment by MaKiPL** [comment]
The best solution to your problem would be uninstalling Avira. You are on Windows and antivirus is scanning the executable as-is it was Windows executable. It's not. It has different header (Microsoft has 'MZ') and your antivirus probably detects system calls which are different on Microsoft and on DexOS. HexTest.exe is totally fine. As @bubach wrote- none antivirus know about DexOS apps. Your antivirus is designed to work with Windows kernel, not DexOS interruption table and system calls. It's ridiculous.

**Comment by m-h-asfour** [comment]
+MaKGPL
This is not "My" problem. This is a problem related to "your" EXE file and the very famous antivirus called Avira that reports that your file contains the famous TR/Crypt.XPACK.Gen.
Avira antivirus is not "My antivirus" despite the fact that I've been using its free version since windows 95 and the level of protection has been acceptable and even if it generates a false alert for a file (or even two) I do not think that uninstalling Avira, or any other antivirus, is "the best" solution for that problem, or an "acceptable solution" for the problem, or even "a solution" for such a problem. 
Both Avira and me know the difference between a zip file and a windows executable file, but Avira scans inside zip files as well. It did not issue any warnings when the zip file was downloaded. Instead, it issued the many warnings when I tried to just unzip the file without any attempt to run any executables.
I understand very well that "your" HEXTEST was written for DexOs not windows, but for a reason that I'm, of course not aware of, you chose to use the EXE extension for "your" different executables. That is the root cause of the problem but apparently it is not the whole problem. 
Avira insists that part of your code inside that executable looks like that famous Trojan, and even when your OS is neither DOS nor Windows, you are still using the usual development tools, at least fasm, tcc, and a C library. Any one of "your" tools may have generated such code that made Avira suspicious, and when the extension of "your" executable is "EXE", the problem is multifold. 
I did not attack you or accuse anyone with deliberately creating this problem, and I did not even take Avira's side.
I do not have time to inspect "your" code and I have no idea how critical is that executable for the operation of your OS, or if its removal for such a purpose is an issue.
I just tried to find a simple solution for the problem for me and others, and I believe that that's far from being ridiculous.

**Pull request closed without merging**
